{
    'name': 'Inmobiliaria',
    'version': '18.0.1.0.0',
    'category': 'Real Estate',
    'summary': 'Gestion de propiedades inmobiliarias',
    'description': 'Modulo para la gestion de propiedades, ofertas y clientes de una inmobiliaria.',
    'author': 'adriifergomm',
    'depends': ['base', 'mail'],
    'data': [
        'security/ir.model.access.csv',
        'views/estate_property_offer_views.xml',
        'views/estate_property_type_views.xml',
        'views/estate_property_tag_views.xml',
        'views/estate_property_views.xml',
        'views/estate_menus.xml',
    ],
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
}
